import {describe,expect,it} from 'vitest'
import {bccA,bccDensity,coordination,rdf,shells,crystalParticles,gasParticles,circuit,burgersVector,sampleModel,type Particle} from '../src/models/order/calculation'
describe('RDF and dislocation checks',()=>{
 it('normalizes a BCC candidate shell to eight, independent of density',()=>{expect(coordination(0,3.05,.06)).toBeCloseTo(8,5);expect(coordination(0,3.05,.12)).toBeCloseTo(8,5);expect(crystalParticles.filter(v=>Math.hypot(...v)<3.05)).toHaveLength(8)})
 it('shows every symmetry-related BCC neighbor in all six plotted shells',()=>{expect(crystalParticles).toHaveLength(64);for(const shell of shells)expect(crystalParticles.filter(v=>Math.abs(Math.hypot(...v)-shell.r)<1e-8)).toHaveLength(shell.count);for(const v of crystalParticles)expect(crystalParticles).toContainEqual(v.map(x=>x===0?0:-x));expect(bccDensity*bccA**3).toBeCloseTo(2,12)})
 it('integrates a density-weighted ordinary gas RDF',()=>{expect(rdf(2,2,.06)).toBe(1);expect(coordination(2,2,.06)).toBeCloseTo(2.0106192983,9);let integral=0;const dr=.0025;for(let i=1;i<=800;i++){const r=(i-.5)*dr;integral+=4*Math.PI*.06*r*r*rdf(2,r,.06)*dr}expect(integral).toBeCloseTo(coordination(2,2,.06),5)})
 it('keeps the ideal gas curve at one at the initial zero-radius limit',()=>{expect(rdf(2,0,.06)).toBe(1);expect(coordination(2,0,.06)).toBe(0)})
 it.each([0,1])('integrates the weighted broadened RDF in mode %i',mode=>{const dr=.001,R=6.5;let count=0;for(let i=0;i<R/dr;i++){const r=(i+.5)*dr;count+=4*Math.PI*.06*r*r*rdf(mode,r,.06)*dr}expect(count).toBeCloseTo(coordination(mode,R,.06),4)})
 it('keeps the seeded gas sample reproducible',()=>{expect(gasParticles).toHaveLength(35);expect(gasParticles[0][0]).toBeCloseTo(-1.360397262033075,12)})
 it.each([0,1])('uses a right-hand traversal and start-to-finish Burgers sign for mode %i',mode=>{const path=circuit(mode,2),b=burgersVector(path);expect(b).toEqual([2,0,0]);expect(burgersVector([...path].reverse())).toEqual([-2,0,0]);const u=path[1].map((x,i)=>x-path[0][i]),v=path[2].map((x,i)=>x-path[1][i]),normal:[number,number,number]=[u[1]*v[2]-u[2]*v[1],u[2]*v[0]-u[0]*v[2],u[0]*v[1]-u[1]*v[0]],line:Particle=mode===0?[1,0,0]:[0,0,1];expect(normal.reduce((s,x,i)=>s+x*line[i],0)).toBeGreaterThan(0);expect(b.reduce((s,x,i)=>s+x*line[i],0)).toBe(mode===0?2:0);const p={reference:0,view:1,material:0,shellRadius:3.05,density:.06,dislocation:mode,spacing:2};expect(sampleModel(p,12).lineDot).toBe(mode===0?2:0)})
})
