import type {FormulaEntry} from '../../framework/types'
import {reactions} from './calculation'
import {chapter,lectureNote} from '../shared/StudyPanel'
export const formulas:FormulaEntry[]=[
 {id:'kv-charge',group:'Defect bookkeeping',title:'Species, site and effective charge',description:'X is the species (including a host atom or vacancy V). Y is a site (Pt, O, i). Superscript is effective, not absolute charge.',tex:[String.raw`X_Y^q,\quad q=z_X-z_{Y,normal}`,String.raw`Pt^{6+},\ O^{2-},\ Ta^{5+},\quad Ta_{Pt}^{\prime}`],sources:['Exam p4 Q2a–d',chapter(3)+' · §3.2–3.3']},
 ...reactions.map((r,i)=>({id:`reaction-${i}`,group:'Defect bookkeeping',title:r.title,description:'Explicit mass, charge and site-balanced formal example. Surface PtO3 is outside the lattice; empty interstitial sites are explicit.',tex:[r.tex],sources:['Exam p4 coverage; reaction derived independently; formal ionic host assumption']})),
 {id:'defect-energy',group:'Defect energies',title:'Activation is not formation',description:'Activation energies determine conditional kinetic weights; formation energies determine equilibrium constants. Schottky in PtO3 is a four-vacancy cluster.',tex:[String.raw`K=\exp(-E_f/k_BT),\quad k_B=8.617333262145\times10^{-5}\ {eV/K}`,String.raw`K_F=c_Vc_i,\quad c_F\simeq K_F^{1/2}`,String.raw`K_S=c_{V_{Pt}}c_{V_O}^3,\quad c_{V_{Pt}}=c_{V_O}\ \Rightarrow\ c_S\simeq K_S^{1/4}`],usage:'Ideal dilute limit, equal normalized site capacities, unit entropy prefactors. Large calculated c violates dilution. Exam calls energies activation energies, so these equilibrium estimates are conditional only.',sources:['Exam p4 Q2a; mass-action derivation',chapter(3)+' · §3.1–3.2']},
 {id:'lecture-defects',group:'Source access',title:'Lecture example · Ta substitution at 3:35',description:lectureNote,tex:[],sources:['https://www.youtube.com/watch?v=i6fOof4oQwc&t=215s · Practice Exam 1 Problem 2 Fall 2026; compact substitution expression inspected at 3:35; explicit reservoir version derived independently']}
]
