import {useId,useMemo} from 'react'
import {useNumberFormat} from '../../framework/formatting'
import type {SimulationSceneProps} from '../../framework/types'
import {MathFormula} from '../../framework/Math'
import {Choice} from '../shared/StudyPanel'
import {reactions,kv,energyComparison} from './calculation'
export function Scene({parameters:p,snapshot:s,display,onParameterChange:change}:SimulationSceneProps){const {format:n}=useNumberFormat(),id=useId(),r=Math.round(p.reaction),e=energyComparison(p.temperature,p.energyMode>=.5)
 const curves=useMemo(()=>[0,1,2].map(i=>Array.from({length:101},(_,j)=>{const T=300+17*j,log=energyComparison(T,p.energyMode>=.5)[i].logFraction;return `${455+j*2.5},${325+Math.max(-75,log)*3}`}).join(' ')),[p.energyMode])
 const anion=r===0,target=anion?1:0,movingX=90+target*65+(345-(90+target*65))*s.progress,movingY=110-48*s.progress
 return <><div className="materials-scene-controls"><Choice label="Example source" value={p.reference} options={['Exam example','Lecture example · substitution']} onChange={v=>{change('reference',v);change('reaction',v===1?3:1);change('species',2);change('site',0);change('charge',-1)}}/>{p.reference===1&&<p className="materials-note">Dr. Joshua Paul Steimel · 3:35: the compact host-incorporation expression shows 2 Ta on Pt sites with one prime each, an oxygen vacancy with two dots, and 5 regular oxygen ions. Our reaction makes the displaced-host reservoir explicit. The unfinished interstitial line in the frame is not copied.</p>}<Choice label="Intrinsic reaction" value={p.reaction} options={['Anion Frenkel','Cation Frenkel','Schottky']} onChange={v=>change('reaction',v)}/><div className="materials-tabs">{reactions.slice(3).map((v,i)=><button key={v.title} aria-pressed={r===i+3} onClick={()=>change('reaction',i+3)}>{v.title}</button>)}</div><Choice label="Species" value={p.species} options={['Pt','O','Ta','Vacancy']} onChange={v=>change('species',v)}/><Choice label="Site" value={p.site} options={['Pt site','O site','Interstitial']} onChange={v=>change('site',v)}/><div className="materials-tabs"><button onClick={()=>{change('species',3);change('site',1);change('charge',2)}}>Easy example · oxygen vacancy</button><button onClick={()=>{change('species',2);change('site',0);change('charge',-1)}}>Exam example · Ta on Pt</button></div><label className="materials-note">Effective charge <input aria-label="Effective charge in scene" type="range" min="-8" max="8" step="1" value={p.charge} onChange={ev=>change('charge',Number(ev.target.value))}/></label></div>
 <svg className="materials-scene" viewBox="0 0 760 430" role="img" aria-labelledby={id}><title id={id}>Schematic PtO3 site motif, {reactions[r].title}, and energy comparison</title>
 {Array.from({length:20},(_,i)=>{const x=90+(i%4)*65,y=110+Math.floor(i/4)*38,isPt=i%4===0,vacant=r<2?i===target:r===2?i<4:r===3?i===1:r===6?isPt:false,ta=(r===3||r===4)&&(i===0||i===4),gone=s.progress>.02&&vacant;return <g key={i}><rect x={x-19} y={y-19} width="38" height="38" fill="none" stroke="#303030"/><circle cx={x} cy={y} r="14" fill={gone?'none':ta?'#d4b184':isPt?'#9db8e8':'#666'} stroke={gone?'#d4b184':'none'} strokeDasharray={gone?'4 3':undefined}/>{display.labels&&<text x={x} y={y+4} textAnchor="middle" fill="#eee">{gone?'V':ta?'Ta':isPt?'Pt':'O'}</text>}</g>})}
 {r<2&&<circle cx={movingX} cy={movingY} r="13" fill={anion?'#999':'#9db8e8'}/>}
 {r===2&&Array.from({length:4},(_,i)=><circle key={i} cx={90+i*65+(335+i%2*18-(90+i*65))*s.progress} cy={110+(238+Math.floor(i/2)*18-110)*s.progress} r="9" fill={i===0?'#9db8e8':'#666'}/>)}
 {r===2&&display.labels&&<text x="320" y="287">PtO₃(s)</text>}
 {r>=5&&Array.from({length:r===5?7:6},(_,i)=><g key={i}><circle cx={70+i*48} cy="62" r="12" fill={r===5&&i>=2?'#666':'#d4b184'}/>{display.labels&&<text x={70+i*48} y="66" textAnchor="middle">{r===5&&i>=2?'O':'Ta'}</text>}</g>)}
 {display.labels&&r>=5&&<text x="55" y="37">{r===5?'2 Taᵢ⁵• + 5 Oᵢ′′':'6 Taᵢ⁵• + 5 V₍Pt₎⁶′ · reservoir: 5 PtO₃'}</text>}
 {r===4&&display.labels&&<text x="55" y="62">Compensation: 2 h•</text>}
 <circle cx={Math.round(p.site)===0?90:Math.round(p.site)===1?155:345} cy={Math.round(p.site)===2?62:110} r="21" fill="none" stroke="#bed3fc" strokeWidth="2"/>
  <text x="55" y="295">Pt : O = 1 : 3 motif</text><text x="55" y="320">Ring = trial site · symbol below.</text><text x="55" y="355" className="accent">{kv(Math.round(p.species),Math.round(p.site),Math.round(p.charge))}</text><text x="55" y="382">{s.chargeValid?'Charge matches this site.':`Expected relative charge ${n(s.effectiveCharge)}.`}</text>
 <line x1="450" y1="325" x2="715" y2="325" stroke="#666"/><line x1="450" y1="95" x2="450" y2="325" stroke="#666"/>{curves.map((pts,i)=><polyline key={i} points={pts} stroke={['#9db8e8','#d4b184','#9ebf9d'][i]} fill="none" strokeWidth="2"/>)}<line x1={455+(p.temperature-300)/1700*250} x2={455+(p.temperature-300)/1700*250} y1="100" y2="325" stroke="#999" strokeDasharray="4 4"/>
 {display.labels&&<><text x="450" y="65">{p.energyMode>=.5?'log₁₀ site fraction (conditional)':'log₁₀ kinetic weight (equal prefactors)'}</text><text x="455" y="350">300 K</text><text x="655" y="350">2000 K</text>{e.map((v,i)=><text key={i} x="455" y={380+i*17} style={{fill:['#9db8e8','#d4b184','#9ebf9d'][i]}}>{['Anion','Cation','Schottky'][i]} · {n(v.energy)} eV → {n(v.logFraction)}</text>)}</>}
 </svg><div className="materials-note"><MathFormula tex={reactions[r].tex}/><p>Mass residual {n(s.massResidual)} · charge residual {n(s.chargeResidual)} · site residual {n(s.siteResidual)}. Zero means balanced. Select species and site to propose a symbol at the ringed site; choose a reaction separately to inspect its fixed balanced terms. Selected reactions are bookkeeping examples, not a prediction of the preferred incorporation mechanism.</p></div><Choice label="Energy interpretation" value={p.energyMode} options={['Activation barrier','Assume formation energy']} onChange={v=>change('energyMode',v)}/><label className="materials-note">Temperature (K) <input aria-label="Temperature slider in scene" type="range" min="300" max="2000" step="10" value={p.temperature} onChange={ev=>change('temperature',Number(ev.target.value))}/></label></>
}
