import type {FormulaEntry} from '../../framework/types'
import {chapter,lectureNote} from '../shared/StudyPanel'
export const formulas:FormulaEntry[]=[
 {id:'lecture-solid-slice',group:'Verified lecture example',title:'Lecture 4 · 1400 °C solid slice',description:lectureNote,tex:[String.raw`\mu_{\mathrm{Cr}}^{\alpha}=\mu_{\mathrm{Cr}}^{\beta},\quad\mu_{\mathrm{Pt}}^{\alpha}=\mu_{\mathrm{Pt}}^{\beta}`],usage:'At 6:07, a horizontal 1400 °C slice and circled (Pt) field are visible. The upper Gibbs drawing is clipped; app curves are independent schematic constructions.',sources:['https://www.youtube.com/watch?v=xdFv_SmjKSA&t=367s · Dr. Joshua Paul Steimel · Practice Exam 1 Problem 4 Fall 2026']},
 {id:'lever-rule',group:'Phase equilibria',title:'Tie lines and phase amounts',description:'Bottom axis is atomic percent Pt, top is weight percent. Atom/mole fractions are used; overall and phase compositions differ.',tex:[String.raw`f_\alpha=(c_\beta-c_0)/(c_\beta-c_\alpha),\quad f_\beta=1-f_\alpha`,String.raw`c_0=f_\alpha c_\alpha+f_\beta c_\beta`],usage:'10 at% at 1500 °C: (Cr)+Cr4Pt, cα≈6.4, cβ≈17.5, fβ≈0.324. Endpoint reading uncertainty ±0.5 at%. No fraction solver outside 1400–1530 °C, 0–35 at%. At 1530 °C eutectic, three fractions require more information.',sources:['Exam p10 Fig4 / p11 Q4b',chapter(4)+' · §4.5']},
 {id:'common-tangent',group:'Free energy',title:'Equality of each chemical potential',description:'Gibbs curves use energy per mole of atoms; x is Pt atomic fraction (at%/100), and g′=dg/dx. The curves are schematic. A common tangent slope is μPt−μCr; the intercepts give the individual potentials.',tex:[String.raw`\mu_{\mathrm{Cr}}=g-xg',\quad\mu_{\mathrm{Pt}}=g+(1-x)g'`,String.raw`\mu_{\mathrm{Cr}}^{\alpha}=\mu_{\mathrm{Cr}}^{\beta},\qquad\mu_{\mathrm{Pt}}^{\alpha}=\mu_{\mathrm{Pt}}^{\beta}`,String.raw`g'=\mu_{\mathrm{Pt}}-\mu_{\mathrm{Cr}}`],usage:'At 1400 °C, two supporting tangents link (Cr)/Cr4Pt and Cr4Pt/(Pt). The lower convex envelope minimizes molar energy. Source diagram does not determine numerical energies.',sources:['Exam p11 Q4c',chapter(4)+' · §4.3–4.4; corrected component-specific tangent interpretation']},
 {id:'phase-rule',group:'Phase equilibria',title:'Fixed-pressure binary phase rule',description:'Two components: Cr and Pt. Count phases separately from components. Imposed constraints are considered after the phase-rule count.',tex:[String.raw`F=C-P+1=3-P`,String.raw`P=1\Rightarrow F=2;\quad P=2\Rightarrow F=1;\quad P=3\Rightarrow F=0`],sources:['Exam p11 Q4b',chapter(4)+' · §4.3']},
 {id:'invariants',group:'Phase transformations',title:'Melting and solid invariants',description:'Eutectics 1571/1530 °C; peritectoid ≈970 °C; eutectoids ≈570/550 °C. CrPt3 at 1134 °C and CrPt near 780 °C are solid ordering maxima.',tex:[String.raw`eutectic:\ L\rightarrow\alpha+\beta`,String.raw`peritectoid:\ \alpha+\beta\rightarrow\gamma,\quad eutectoid:\ \alpha\rightarrow\beta+\gamma`],usage:'Congruent melting: Cr 1863 °C, Cr4Pt 1599 °C (near 19.1 at%), (Pt) maximum 1784 °C / 76.7 at%, shallow approximate minimum near 96 at% / 1760 °C, pure Pt 1769 °C. A two-phase congruent point is not a binary three-phase invariant.',sources:['Exam p10 Fig4; unlabeled extrema/invariants are approximate',chapter(4)+' · §4.6–4.8']},
]
