import {useNumberFormat} from '../../framework/formatting'
import type {SimulationLessonProps} from '../../framework/types'
import {StudyPanel,Equation,numericAnswer} from '../shared/StudyPanel'
import {phaseNames,lever,chemicalPotentials,tangentContacts} from './calculation'
import {events} from './boundaries'
export function Lesson({parameters:p,snapshot:s}:SimulationLessonProps){const {format:n}=useNumberFormat(),view=Math.round(p.view),event=events[Math.round(p.cooling)],mu=chemicalPotentials(0,tangentContacts[0]),muRight=chemicalPotentials(1,tangentContacts[2])
 const label=s.phases===3?'Cr₄Pt + L + (Pt)':s.phases===1?phaseNames[s.phaseA]:phaseNames[s.phaseA]+' + '+phaseNames[s.phaseB]
 const result=view===1?<Equation tex={String.raw`\begin{aligned}\mu_{Cr}&=g-xg'\\\mu_{Pt}&=g+(1-x)g'\end{aligned}`}>Left tangent schematic intercepts: μCr={n(mu.Cr)}, μPt={n(mu.Pt)} at 5.6 / 17.5 at% Pt. Right tangent: μCr={n(muRight.Cr)}, μPt={n(muRight.Pt)} at 22.3 / 33.2 at% Pt. All are arbitrary energy/mol. Each component has the same potential at the two contacts of its tangent. Slope = μPt−μCr, not both chemical potentials.</Equation>:view===2?<p>{event.before} → {event.after}; {event.kind} at {n(event.T)} °C. Three phases coexist during the reaction, so F=3−3=0.</p>:view===3?<p>1571 and 1530 °C are eutectics. ≈970 °C is a peritectoid; ≈570 and ≈550 °C are eutectoids. Congruent melting extrema and solid ordering maxima are different events.</p>:s.fractionValid?<Equation tex={String.raw`f_\alpha=\frac{c_\beta-c_0}{c_\beta-c_\alpha},\qquad f_\beta=1-f_\alpha`}>{s.phases===1?'Single phase: fraction = 1.':`fα = (${n(s.right)} − ${n(p.composition)}) / (${n(s.right)} − ${n(s.left)}) ≈ ${n(s.fA)}; fβ ≈ ${n(s.fB)}.`}</Equation>:<p>Three-phase fractions are underdetermined here. A transformation extent or another constraint is needed.</p>
 const question=view===1?{prompt:'Does a common tangent establish equality of each component’s chemical potential between phases?',choices:['Yes, each component','Only the slope','Both potentials equal each other'],hint:'Tangent intercept at x=0 gives μCr, at x=1 gives μPt.',check:(a:string)=>a==='Yes, each component',solution:'μCrα=μCrβ and μPtα=μPtβ; μCr need not equal μPt.'}:view===2||view===3?{prompt:'At fixed pressure, how many phase-rule degrees of freedom does a binary three-phase invariant have?',hint:'F=C−P+1=2−3+1.',check:(a:string)=>numericAnswer(a,0),solution:'0. A congruent two-phase melting extremum is not a three-phase invariant.'}:{prompt:'Easy tie line: cα=5 at% Pt, cβ=15 at% Pt, c₀=10 at% Pt. Enter the right-phase atom fraction.',hint:'(10−5)/(15−5); midpoint means equal atom/mole fractions.',check:(a:string)=>numericAnswer(a,lever(10,5,15).right),solution:'0.5; left fraction is also 0.5.'}
 return <StudyPanel method={view===1?String.raw`\mu_{Cr}^{\alpha}=\mu_{Cr}^{\beta},\quad\mu_{Pt}^{\alpha}=\mu_{Pt}^{\beta}`:view===0?String.raw`f_\beta=\frac{c_0-c_\alpha}{c_\beta-c_\alpha}`:String.raw`F=3-P`} key={view} title={['Divide the tie line','Read the tangent intercepts','Cool through an invariant','Name the transformations'][view]} steps={[<p>Predict {view===0?'whether overall composition equals either phase composition.':view===1?'whether a phase mixture can lie below both single-phase curves.':'which phases appear when cooling through the selected reaction.'}</p>,<p>The source temperature axis is °C. Bottom composition axis is atomic percent Pt; top axis is weight percent. The numeric lesson uses the bottom axis and atom/mole fractions. Components are Cr and Pt; phases are distinct structures or solutions.</p>,result,<>{result}<p>Current solid slice at {n(s.temperature)} °C: {label}. Phase count P={n(s.phases)}; fixed-pressure phase rule F=3−P={n(s.freedom)}.</p></>,<p>{view===1?'At 1400 °C, stable fields are (Cr), (Cr)+Cr₄Pt, Cr₄Pt, Cr₄Pt+(Pt), and (Pt). The two tangent segments encode equality of μCr across each coexisting pair and equality of μPt across that pair. A phase diagram does not supply numerical Gibbs energies.':view===0?'Exam: 10 at% Pt at 1500 °C gives (Cr)+Cr₄Pt. Our graph readings cα≈6.4 and cβ≈17.5 give fCr≈0.676 and fCr₄Pt≈0.324. Endpoints are graph estimates, not exact material data. F=1 for two phases at fixed pressure. Fixing T consumes that intensive freedom; fixing the overall composition sets amounts through the lever rule, not a new intensive phase-rule variable.':'Congruent melting converts solid to liquid at the same composition. Eutectic L→two solids, peritectoid two solids→one solid, eutectoid one solid→two solids. The lower domes occur within a solid field, so they do not describe melting.'}</p>,<p>Use Practice for a nearby check. In Explore, inspect the current substitution, then return to the source overview.</p>]} explore={<>{result}<p>Boundary uncertainty ±0.5 at% means phase fractions near a boundary are especially sensitive. For the exam point, varying both endpoints within that uncertainty puts the Cr₄Pt atom fraction roughly between 0.279 and 0.369. Numerical fractions at three-phase coexistence are deliberately withheld.</p><p>At fixed pressure, F=3−P. Fixing a temperature or chemical potential is an additional imposed constraint. Overall composition controls phase amounts in a two-phase field.</p></>} question={question} source="Exam p10 Fig4 / p11 Q4. Manually digitized high-temperature solid slice in boundaries.ts; linear interpolation, ±0.5 at% readings. 10% is interpreted as atomic percent using the bottom axis; a weight-percent interpretation would require conversion and give a different state. Overview, cooling, and Gibbs curves are schematic, not assessed thermodynamics."/>
}
