import {defineSimulation} from '../../framework/model'
import {sampleModel,getPlayback} from './calculation'
import {Scene} from './Scene'
import {Lesson} from './Lesson'
import {formulas} from './formulas'
import {getSnapshotNotes,getSnapshotReport} from './snapshot'
import {thermalCases} from './thermal'
import {events,congruent} from './boundaries'
import './styles.css'
export const phasesModel=defineSimulation({id:'phases',title:'Cr–Pt phase equilibria',eyebrow:'LAB D · EXAM QUESTION 4',description:'Connect the phase diagram to phase amounts and the lowest Gibbs energy.',interactionHint:'Numerical readings: 0–35 at% Pt, 1400–1530 °C. Graph estimates carry ±0.5 at% uncertainty.',defaults:{reference:0,view:0,temperature:1500,composition:10,cooling:0,gRange:0},controls:[
 {key:'reference',label:'Example source',group:'Example',min:0,max:1,step:1,visibleWhen:()=>false,options:[{value:0,label:'Practice exam'},{value:1,label:'Lecture · 1400 °C slice'}]},
 {key:'view',label:'Explore',group:'Example',min:0,max:3,step:1,options:[{value:0,label:'Exam tie line & fractions'},{value:1,label:'G–composition · 1400 °C'},{value:2,label:'Cooling & G–T'},{value:3,label:'Full phase-diagram overview'}]},
 {key:'temperature',label:'Solid-slice temperature',group:'Tie line',unit:'°C',min:1400,max:1530,step:1,visibleWhen:p=>p.view===0,note:'Supported graph readings: 1400–1530 °C. At 1530 °C, three-phase fractions require more information.'},
 {key:'composition',label:'Overall Pt composition',group:'Composition',unit:'at% Pt',min:0,max:35,step:.1,visibleWhen:p=>p.view===0||p.view===1,note:'Uses the bottom atomic-percent axis. The resulting phase fractions are atomic/mole fractions.'},
 {key:'gRange',label:'Gibbs composition range',group:'Graph',min:0,max:1,step:1,visibleWhen:p=>p.view===1,options:[{value:0,label:'Zoom · 0–40 at% Pt'},{value:1,label:'Whole binary · 0–100 at% Pt'}]},
 {key:'cooling',label:'Transformation',group:'Cooling & G–T',min:0,max:9,step:1,visibleWhen:p=>p.view===2,options:thermalCases.map((event,value)=>({value,label:event.title+' · '+event.T+' °C'})),note:'Phase-diagram and Gibbs-temperature markers move together. The two branches compare equal-composition assemblages; energies and cooling speed are schematic.'}
 ],sample:sampleModel,getPlayback,getSnapshotNotes,getSnapshotReport,getReadouts:(p,s)=>Math.round(p.view)===2?[{label:'Demonstration temperature',value:s.coolingTemperature,unit:'°C'},{label:'Transition temperature',value:s.invariantTemperature,unit:'°C'},{label:'Products − reactants Δg',value:s.gap,unit:'arb. / mol atoms'},{label:'At transition F',value:s.transitionFreedom}]:Math.round(p.view)===3?[{label:'Marked melting extrema',value:congruent.length},{label:'Eutectic invariants',value:events.filter(e=>e.kind==='Eutectic').length},{label:'Peritectoid invariants',value:events.filter(e=>e.kind.startsWith('Peritectoid')).length},{label:'Eutectoid invariants',value:events.filter(e=>e.kind.startsWith('Eutectoid')).length}]:s.fractionValid?[{label:'Left phase composition',value:s.left,unit:'at% Pt'},{label:'Right phase composition',value:s.right,unit:'at% Pt'},{label:'Left phase atom fraction',value:s.fA},{label:'Right phase atom fraction',value:s.fB}]:[{label:'Three-phase count',value:3},{label:'Invariant liquid composition',value:28.1,unit:'at% Pt'},{label:'Phase rule F',value:0},{label:'Fraction solution available',value:0}],Scene,Lesson,formulas,guides:[{title:'Read the correct axis',text:'Exam Fig4: °C, bottom atomic percent Pt, top weight percent Pt. The 10% problem is interpreted using the bottom at% axis, explicitly stated. Components Cr and Pt; phases (Cr), Cr4Pt.'},{title:'Digitization limits',text:'High-temperature solid boundaries are manually read and interpolated. ±0.5 at% uncertainty. Numerical sliders stop at 0–35 at% and 1400–1530 °C. Overview and energy curves are schematic. The exam’s printed Cr₃Pt label conflicts with its drawn 33–40 at% field (nominal Cr₃Pt is 25 at% Pt); displayed graph coordinates are not formula stoichiometry.'}]})
