import {defineSimulation} from '../../framework/model'
import {sampleModel,getPlayback} from './calculation'
import {Scene} from './Scene'
import {Lesson} from './Lesson'
import {formulas} from './formulas'
import {getSnapshotNotes} from './snapshot'
import './styles.css'
export const orderModel=defineSimulation({id:'order',title:'Order & dislocations',eyebrow:'LAB C · EXAM QUESTION 3',description:'From a neighbor shell to a distribution, then a line defect.',interactionHint:'The exam graph is schematic. Coordination supports a structure candidate, not a unique element.',defaults:{reference:0,view:0,material:0,shellRadius:3.05,density:.06,dislocation:0,spacing:1},controls:[
 {key:'reference',label:'Example source',group:'Example',min:0,max:1,step:1,visibleWhen:()=>false,options:[{value:0,label:'Practice exam'},{value:1,label:'Lecture · order sketches'}]},
 {key:'view',label:'Explore',group:'Example',min:0,max:1,step:1,options:[{value:0,label:'Radial distribution & neighbors'},{value:1,label:'Burgers circuit'}]},
 {key:'material',label:'Material model',group:'Radial distribution',min:0,max:2,step:1,visibleWhen:p=>p.view===0,options:[{value:0,label:'Crystal · BCC candidate'},{value:1,label:'Semicrystalline polymer'},{value:2,label:'Ideal gas'}]},
 {key:'shellRadius',label:'Final neighbor-shell radius',group:'Radial distribution',unit:'Å',min:.1,max:6.5,step:.05,visibleWhen:p=>p.view===0,note:'The expanding shell ends at this radius. Coordination counts neighbors within the shell.'},
 {key:'density',label:'Number density',group:'Radial distribution',unit:'Å⁻³',min:.01,max:.12,step:.005,visibleWhen:p=>p.view===0,note:'Used in N(R) = 4πρ ∫ r²g(r) dr. Crystal shell counts stay fixed as normalization changes.'},
 {key:'dislocation',label:'Dislocation type',group:'Burgers circuit',min:0,max:1,step:1,visibleWhen:p=>p.view===1,options:[{value:0,label:'Screw · b parallel to the line'},{value:1,label:'Edge · b perpendicular to the line'}]},
 {key:'spacing',label:'Burgers vector magnitude',group:'Burgers circuit',unit:'Å',min:.5,max:2,step:.1,visibleWhen:p=>p.view===1,note:'Uses the instructor’s start-to-finish/right-hand convention: b = finish − start.'}
 ],sample:sampleModel,getPlayback,getSnapshotNotes,getReadouts:(p,s)=>Math.round(p.view)===0?[{label:'Current shell radius',value:s.shell,unit:'Å'},{label:'Integrated coordination',value:s.coordination},{label:'g(r) · dimensionless',value:s.g},{label:'BCC candidate lattice a',value:s.a,unit:'Å'}]:[{label:'Burgers vector magnitude',value:s.burgers,unit:'Å'},{label:'b · unit tangent t',value:s.lineDot,unit:'Å'},{label:'Line-defect dimension',value:1},{label:'Construction progress',value:100*s.progress,unit:'%'}],Scene,Lesson,formulas,guides:[{title:'Exam graph normalization',text:'Figure 2 labels g(r) but calls the peak integral 8 without stating radial weighting. We treat 8 as the given coordination, not the unweighted integral of ordinary dimensionless g.'},{title:'Screw circuit convention',text:'Exam Fig3 is a screw stepped surface. It supplies no directed circuit. App circuit is independently constructed using the instructor’s SF/RH convention: b joins start to finish in a right-hand circuit. Reversing both the circuit and positive line reverses b.'}]})
