import {useId,useMemo} from 'react'
import {useNumberFormat} from '../../framework/formatting'
import type {SimulationSceneProps} from '../../framework/types'
import {Choice} from '../shared/StudyPanel'
import {crystalParticles,polymerParticles,gasParticles,rdf,circuit,type Particle} from './calculation'
export function Scene({parameters:p,snapshot:s,display,onParameterChange:change}:SimulationSceneProps){const {format:n}=useNumberFormat(),id=useId(),mode=Math.round(p.material),view=Math.round(p.view),screw=Math.round(p.dislocation)===0
 const profile=useMemo(()=>Array.from({length:401},(_,i)=>{const r=i*.0175;return [r,rdf(mode,r,p.density)]}),[mode,p.density]);const maximum=Math.max(1,...profile.map(v=>v[1]))
 const project=(v:Particle):[number,number]=>[210+23*v[0]+10*v[2],215+23*v[1]-8*v[2]]
 const particles=[crystalParticles,polymerParticles,gasParticles][mode]
 const path=circuit(Math.round(p.dislocation),p.spacing),pr=(v:Particle):[number,number]=>screw?[160+35*v[1]+28*v[0],295-35*v[2]-13*v[0]]:[160+35*v[0],295-35*v[1]]
 const f=s.progress*4,segment=Math.min(3,Math.floor(f)),fraction=f-segment,tip=path[segment].map((x,i)=>x+(path[segment+1][i]-x)*fraction) as Particle
 return <><div className="materials-scene-controls"><Choice label="Example source" value={p.reference} options={['Exam example','Lecture example · order sketches']} onChange={v=>{change('reference',v);change('view',0);change('material',v===1?1:0);change('shellRadius',v===1?6.5:3.05)}}/>{p.reference===1&&<p className="materials-note">Dr. Joshua Paul Steimel · 2:49: the observed sketch combines sharp and broad peaks for the polymer and a flat gas curve. The interactive curves use our documented normalization and idealized mixture. Handwriting naming the element is not sufficiently clear to transcribe.</p>}<Choice label="Inspect" value={p.view} options={['RDF & neighbors','Burgers circuit']} onChange={v=>{change('view',v);if(v!==0)change('reference',0)}}/>{view===0?<><Choice label="Material idealization" value={p.material} options={['Exam crystal · BCC candidate','Semicrystalline polymer','Ideal gas']} onChange={v=>change('material',v)}/><div className="materials-tabs"><button onClick={()=>{change('material',2);change('density',.06);change('shellRadius',2)}}>Easy example · gas at R=2 Å</button><button onClick={()=>{change('material',0);change('shellRadius',3.05)}}>Exam example · 8 neighbors</button></div><label className="materials-note">Final shell radius <input aria-label="Final shell radius in scene" type="range" min=".1" max="6.5" step=".05" value={p.shellRadius} onChange={e=>change('shellRadius',Number(e.target.value))}/></label></>:<Choice label="Line character" value={p.dislocation} options={['Exam · screw','Nearby · edge']} onChange={v=>change('dislocation',v)}/>}</div>
 {view===0?<svg className="materials-scene" viewBox="0 0 760 420" role="img" aria-labelledby={id}><title id={id}>Particle positions linked to a three-dimensional radial distribution and coordination</title><circle cx="210" cy="215" r={s.shell*23} stroke="#9db8e8" fill="#9db8e808" strokeDasharray="5 4"/>{particles.map((v,i)=><circle key={i} cx={project(v)[0]} cy={project(v)[1]} r="4" fill={Math.hypot(...v)<=s.shell?'#9db8e8':'#444'}/>)}<circle cx="210" cy="215" r="6" fill="#d4b184"/>
 <path d="M430,325 H715 M430,325 V80" fill="none" stroke="#666"/><polyline points={profile.map(([r,g])=>`${430+r/7*285},${325-225*g/maximum}`).join(' ')} fill="none" stroke="#9db8e8" strokeWidth="2"/>{display.forces&&<polygon points={`430,325 ${profile.filter(([r])=>r<=s.shell).map(([r,g])=>`${430+r/7*285},${325-225*g/maximum}`).join(' ')} ${430+s.shell/7*285},325`} fill="#9db8e829"/>}<line x1={430+s.shell/7*285} x2={430+s.shell/7*285} y1="85" y2="325" stroke="#d4b184"/>
 {display.labels&&<><text x="55" y="45">3D neighbors · projected positions</text><text x="430" y="45">g(r), dimensionless</text><text x="55" y="380">N(R) = {n(s.coordination)}</text><text x="430" y="350">0</text><text x="673" y="350">7 Å</text><text x="440" y="80">max {n(maximum)}</text><text x="430" y="380">R = {n(s.shell)} Å</text></>}
 </svg>:<svg className="materials-scene" viewBox="0 0 760 420" role="img" aria-labelledby={id}><title id={id}>{screw?'Screw':'Edge'} dislocation and independently constructed right-hand Burgers circuit</title><defs><marker id={`${id}-b-arrow`} viewBox="0 0 10 10" refX="9" refY="5" markerWidth="5" markerHeight="5" orient="auto-start-reverse"><path d="M0 0 L10 5 L0 10 z" fill="#d4b184"/></marker><marker id={`${id}-line-arrow`} viewBox="0 0 10 10" refX="9" refY="5" markerWidth="5" markerHeight="5" orient="auto-start-reverse"><path d="M0 0 L10 5 L0 10 z" fill="#9db8e8"/></marker></defs>
 {screw?Array.from({length:9},(_,i)=><g key={i}><path d={`M65,${115+i*18} L290,${115+i*18} L315,${100+i*18} L450,${100+i*18}`} fill="none" stroke="#454545"/><path d={`M${65+i*43},115 L${65+i*43},255 L${45+i*43},325`} fill="none" stroke="#333"/></g>):Array.from({length:9},(_,i)=><g key={i}><line x1="65" x2="440" y1={105+i*24} y2={105+i*24} stroke="#333"/><path d={`M${65+i*43},105 L${65+i*43},${i===4?215:345}`} stroke="#444" fill="none"/></g>)}
 <polyline points={(screw?[[0,0,0],[0,4*p.spacing,0],[0,4*p.spacing,4*p.spacing],[0,0,4*p.spacing],[0,0,0]] as Particle[]:[...path.slice(0,4),path[0]]).map(v=>pr(v).join(',')).join(' ')} stroke="#777" strokeDasharray="4 4" fill="none"/>
 <polyline points={[...path.slice(0,segment+1),tip].map(v=>pr(v).join(',')).join(' ')} stroke="#9db8e8" strokeWidth="3" fill="none" markerEnd={`url(#${id}-line-arrow)`}/>{s.progress>.95&&<line x1={pr(path[0])[0]} y1={pr(path[0])[1]} x2={pr(path[4])[0]} y2={pr(path[4])[1]} stroke="#d4b184" strokeWidth="3" markerEnd={`url(#${id}-b-arrow)`}/>}<circle cx={pr(tip)[0]} cy={pr(tip)[1]} r="6" fill="#9db8e8"/>
 <line x1="525" y1="155" x2="665" y2="155" stroke="#d4b184" strokeWidth="3" markerEnd={`url(#${id}-b-arrow)`}/>{screw&&<line x1="525" y1="205" x2="665" y2="205" stroke="#9db8e8" strokeWidth="3" markerEnd={`url(#${id}-line-arrow)`}/>}{!screw&&<line x1="595" y1="235" x2="595" y2="105" stroke="#9db8e8" strokeWidth="3" markerEnd={`url(#${id}-line-arrow)`}/>}
 {display.labels&&<><text x="500" y="85" className="large-label">{screw?'SCREW':'EDGE'}</text><text x="500" y="138">gold: b · blue: unit tangent t</text><text x="500" y="280">{screw?'b ∥ t (parallel here)':'b ⟂ t'}</text><text x="500" y="250">{screw?"t = +x (unit)":"t = +z (unit)"}</text><text x={pr(path[0])[0]-12} y={pr(path[0])[1]+20}>S</text>{s.progress>.95&&<text x={pr(path[4])[0]+8} y={pr(path[4])[1]-10}>F</text>}<text x="500" y="310">b = ({n(p.spacing)}, 0, 0) Å</text><text x="40" y="380">SF/RH · gold b goes start → finish</text></>}
 </svg>}<p className="materials-note">{view===0?mode===0?'First verified exam distance: 2.78 Å. Given first-shell coordination: 8. BCC is a candidate; later spikes here are ideal BCC shells, not digitized exam measurements. The projected ideal lattice covers all six shown shells. Particle highlights use exact distances; broadened RDF coordination changes smoothly near a shell. Shading selects r ≤ R; coordination includes the 4πρr² weighting.':mode===1?'Model: bonded-chain peak plus 30% crystalline correlations and an amorphous background beyond 2 Å. Crystallites have long-range order locally; bulk order is limited by domains. The short projected chain is illustrative and is not used to estimate this bulk RDF.':'Ideal uncorrelated gas: g(r)=1. Projected particles are illustrative; the bulk curve is analytic, not estimated from this small sample.':'Instructor’s SF/RH convention: right-hand circuit around positive unit line tangent t: +x (screw) or +z (edge); b points start → finish. The opposite vector closes the gap. Reversing both traversal and line sense reverses b. Exam Fig3 shows a screw surface but no directed step counts; this trace is a separate teaching construction.'}</p></>
}
