import {useId,useMemo} from 'react'
import {useNumberFormat} from '../../framework/formatting'
import type {SimulationSceneProps} from '../../framework/types'
import {Choice} from '../shared/StudyPanel'
import {crystalParticles,polymerParticles,gasParticles,rdf,type Particle} from './calculation'
import {DislocationScene} from './DislocationScene'
export function Scene({parameters:p,snapshot:s,display,onParameterChange:change,onSeek,playing,onReplay,onTogglePlayback}:SimulationSceneProps){const {format:n}=useNumberFormat(),id=useId(),mode=Math.round(p.material),view=Math.round(p.view)
 const profile=useMemo(()=>Array.from({length:401},(_,i)=>{const r=i*.0175;return [r,rdf(mode,r,p.density)]}),[mode,p.density]);const maximum=Math.max(1,...profile.map(v=>v[1]))
 const project=(v:Particle):[number,number]=>[210+23*v[0]+10*v[2],215+23*v[1]-8*v[2]]
 const particles=[crystalParticles,polymerParticles,gasParticles][mode]
 return <><div className="materials-scene-controls"><Choice label="Example source" value={p.reference} options={['Exam example','Lecture example · order sketches']} onChange={v=>{change('reference',v);change('view',0);change('material',v===1?1:0);change('shellRadius',v===1?6.5:3.05)}}/>{p.reference===1&&<p className="materials-note">Dr. Joshua Paul Steimel · 2:49: the observed sketch combines sharp and broad peaks for the polymer and a flat gas curve. The interactive curves use our documented normalization and idealized mixture. Handwriting naming the element is not sufficiently clear to transcribe.</p>}<Choice label="Inspect" value={p.view} options={['RDF & neighbors','Burgers circuit']} onChange={v=>{change('view',v);if(v!==0)change('reference',0)}}/>{view===0?<><Choice label="Material idealization" value={p.material} options={['Exam crystal · BCC candidate','Semicrystalline polymer','Ideal gas']} onChange={v=>change('material',v)}/><div className="materials-tabs"><button onClick={()=>{change('material',2);change('density',.06);change('shellRadius',2)}}>Easy example · gas at R=2 Å</button><button onClick={()=>{change('material',0);change('shellRadius',3.05)}}>Exam example · 8 neighbors</button></div><label className="materials-note">Final shell radius <input aria-label="Final shell radius in scene" type="range" min=".1" max="6.5" step=".05" value={p.shellRadius} onChange={e=>change('shellRadius',Number(e.target.value))}/></label></>:<Choice label="Line character" value={p.dislocation} options={['Exam · screw','Nearby · edge']} onChange={v=>change('dislocation',v)}/>}</div>
 {view===0?<svg className="materials-scene" viewBox="0 0 760 420" role="img" aria-labelledby={id}><title id={id}>Particle positions linked to a three-dimensional radial distribution and coordination</title><circle cx="210" cy="215" r={s.shell*23} stroke="#9db8e8" fill="#9db8e808" strokeDasharray="5 4"/>{particles.map((v,i)=><circle key={i} cx={project(v)[0]} cy={project(v)[1]} r="4" fill={Math.hypot(...v)<=s.shell?'#9db8e8':'#444'}/>)}<circle cx="210" cy="215" r="6" fill="#d4b184"/>
 <path d="M430,325 H715 M430,325 V80" fill="none" stroke="#666"/><polyline points={profile.map(([r,g])=>`${430+r/7*285},${325-225*g/maximum}`).join(' ')} fill="none" stroke="#9db8e8" strokeWidth="2"/>{display.forces&&<polygon points={`430,325 ${profile.filter(([r])=>r<=s.shell).map(([r,g])=>`${430+r/7*285},${325-225*g/maximum}`).join(' ')} ${430+s.shell/7*285},325`} fill="#9db8e829"/>}<line x1={430+s.shell/7*285} x2={430+s.shell/7*285} y1="85" y2="325" stroke="#d4b184"/>
 {display.labels&&<><text x="55" y="45">3D neighbors · projected positions</text><text x="430" y="45">g(r), dimensionless</text><text x="55" y="380">N(R) = {n(s.coordination)}</text><text x="430" y="350">0</text><text x="673" y="350">7 Å</text><text x="440" y="80">max {n(maximum)}</text><text x="430" y="380">R = {n(s.shell)} Å</text></>}
 </svg>:<DislocationScene parameters={p} snapshot={s} display={display} onSeek={onSeek} playing={playing} onReplay={onReplay} onTogglePlayback={onTogglePlayback}/>}{view===0&&<p className="materials-note">{mode===0?'First verified exam distance: 2.78 Å. Given first-shell coordination: 8. BCC is a candidate; later spikes here are ideal BCC shells, not digitized exam measurements. The projected ideal lattice covers all six shown shells. Particle highlights use exact distances; broadened RDF coordination changes smoothly near a shell. Shading selects r ≤ R; coordination includes the 4πρr² weighting.':mode===1?'Model: bonded-chain peak plus 30% crystalline correlations and an amorphous background beyond 2 Å. Crystallites have long-range order locally; bulk order is limited by domains. The short projected chain is illustrative and is not used to estimate this bulk RDF.':'Ideal uncorrelated gas: g(r)=1. Projected particles are illustrative; the bulk curve is analytic, not estimated from this small sample.'}</p>}</>
}
