import { useNumberFormat } from '../../framework/formatting'
import type { SimulationLessonProps } from '../../framework/types'
import { StudyPanel,Equation,numericAnswer } from '../shared/StudyPanel'
import { Indices } from './Notation'
import { structures,indexAnswer,planeData,directionPoints,type V3 } from './calculation'
export function Lesson({parameters:p,snapshot:s}:SimulationLessonProps){const {format:n}=useNumberFormat();const view=Math.round(p.view),st=structures[view===3?1:Math.round(p.structure)]
 let intercepts:V3|null=null
 try {const data=planeData(p);if(data.level!==0)intercepts=data.normal.map(v=>v===0?0:data.level/v) as V3}catch{/* The scene and sample flag unsupported coordinates. */}
 const interceptText=intercepts?.map(v=>v===0?'∞':n(v)).join(', '),reciprocalText=intercepts?.map(v=>v===0?'0':n(1/v)).join(', ')
 const {start,end}=directionPoints(p);const dir=<Indices values={[s.u,s.v,s.w]}/>,plane=<Indices values={[s.h,s.k,s.l]} kind="plane"/>
 const result=view===0?<p>{st.count}; nearest neighbors = {n(st.nn)}. a/R = {n(st.factor)}.</p>:view===1?<Equation tex={String.raw`[uvw]=\operatorname{reduce}(\mathbf r_{end}-\mathbf r_{start})`}>({n(end[0]-start[0])}, {n(end[1]-start[1])}, {n(end[2]-start[2])}) → {s.validDirection?dir:'undefined'}</Equation>:view===2?<Equation tex={String.raw`(hkl)=\operatorname{integerize}(1/x,1/y,1/z)`}>{intercepts?<span>Intercepts ({interceptText}) → reciprocals ({reciprocalText}). Current integer plane indices: {s.validPlane?plane:'undefined'}. Integer equation level: {n(s.planeLevel)}; keep this offset when clearing fractions.</span>:'This plane passes through the origin: translate it off the origin before reading intercepts.'} Parallel axis → index 0. Translation retains orientation.</Equation>:<Equation tex={String.raw`PD_{BCC(200)}=\frac{1}{a^2},\qquad a=\frac{4R}{\sqrt3}`}>a = {n(4*p.radius/Math.sqrt(3))} Å; PD = {n(s.planarDensity)} atoms/Å².</Equation>
 const question=view===1?{prompt:'Nearby direction: tail (1,0,1), head (0,1,1). Enter three signed integer indices.',hint:'Head minus tail gives (−1,1,0). Keep the negative x sign.',check:(a:string)=>indexAnswer(a,[-1,1,0]),solution:'[−1 1 0].'}:view===2?{prompt:'Nearby plane: intercepts (1/2, 1, ∞). Enter three Miller indices.',hint:'Take reciprocals. Parallel z has reciprocal zero. Do not divide away the 2.',check:(a:string)=>indexAnswer(a,[2,1,0]),solution:'(2 1 0).'}:view===3?{prompt:'Easy BCC (200): a = 2 Å. What is the planar atom density in atoms/Å²?',hint:'One whole atom divided by a² = 4 Å².',check:(a:string)=>numericAnswer(a,.25),solution:'0.25 atoms/Å².'}:{prompt:'How many atoms belong to one FCC conventional cell?',hint:'Eight corners each count 1/8; six face centers each count 1/2.',check:(a:string)=>numericAnswer(a,4),solution:'4 atoms.'}
 return <StudyPanel method={view===0?String.raw`N=8(1/8)+N_{interior}+N_{faces}/2`:view===1?String.raw`[uvw]=\operatorname{reduce}(\mathbf r_{end}-\mathbf r_{start})`:view===2?String.raw`(hkl)=\operatorname{integerize}(1/x,1/y,1/z)`:String.raw`PD=N/A`} key={view} title={['Share the atoms','Read the arrow','Invert the intercepts','Count the slice'][view]} steps={[
 <p>Predict {view===1?'the signs before calculating. Does the arrow move down z?':view===2?'which axis the plane is parallel to.':view===3?'whether any corner center lies at x=a/2.':'how much of a boundary atom belongs to this cell.'}</p>,
 <p>Choose an easy example or the exam geometry beside the cell. Rotate it, then inspect the axes. Customize contains tail/head, signed indices, intercepts, plane level, and radius.</p>,result,
 <>{result}<p>Round only displayed values; calculation keeps full precision. Plane indices specify a normal; the separate level locates the drawn slice.</p></>,
 <p>{view===1?'Exam D is [1 0 −2]. A’s upper, left, and lower arrows belong to ⟨210⟩ by cubic symmetry; the right arrow is ⟨110⟩. None is an SC touching ⟨100⟩ chain.':view===2?'[uvw] is one direction; ⟨uvw⟩ is its symmetry family. (hkl) is one plane orientation; {hkl} is its family. Exam B crosses the origin: translate before using intercepts.':view===3?'Atom density counts atom centers per area. Packing fraction counts the circular area covered by atoms; the two have different units.':st.dense}</p>,<p>Switch to Practice for a nearby checked question. Use Hint to locate the step you need.</p>
 ]} explore={<>{result}<p>{st.dense}</p><p>SC: a=2R, 1 atom, 6 NN. BCC: a=4R/√3, 2 atoms, 8 NN. FCC: a=2√2R, 4 atoms, 12 NN.</p></>} question={question} source="Exam p1 Fig1 and Q1a–d. Textbook §2.3–2.6. A arrows and B’s half-edge intercept use intended midpoint readings; the source drawing is not metrically exact. B=(2 1 −1), C=(0 1 1) under that reading. No close-packed planes in SC/BCC."/>
}
