import { useId, useRef } from 'react'
import { useNumberFormat } from '../../framework/formatting'
import type { SimulationSceneProps } from '../../framework/types'
import { Choice } from '../shared/StudyPanel'
import { corners,edges,examArrows,structures,planeData,planePolygon,indexText,type V3 } from './calculation'
export function Scene({parameters:p,snapshot:s,display,onParameterChange:change,onInteractionStart,onInteractionEnd}:SimulationSceneProps) {
 const {format:n}=useNumberFormat();const id=useId();const drag=useRef<{x:number;yaw:number}|null>(null);const view=Math.round(p.view),structure=view===3?1:Math.round(p.structure),st=structures[structure]
 const project=(v:V3):[number,number]=>{const a=p.yaw*Math.PI/180,x=(v[0]-.5)*Math.cos(a)-(v[1]-.5)*Math.sin(a),y=(v[0]-.5)*Math.sin(a)+(v[1]-.5)*Math.cos(a);return [320-115*x+165*y,225+65*x+25*y-185*(v[2]-.5)]}
 const points:V3[]=[...corners,...(structure===1?[[.5,.5,.5] as V3]:structure===2?[[0,.5,.5],[1,.5,.5],[.5,0,.5],[.5,1,.5],[.5,.5,0],[.5,.5,1]] as V3[]:[])]
 const start:V3=[p.sx,p.sy,p.sz],end:V3=[p.ex,p.ey,p.ez];const head=start.map((v,i)=>v+(end[i]-v)*s.progress) as V3;const pd=planeDataSafe();function planeDataSafe(){try{return planeData(p)}catch{return {normal:[0,0,0] as V3,level:1,indices:[0,0,0] as V3}}}
 const poly=view===3?planePolygon([1,0,0],.5):planePolygon(pd.normal,pd.level)
 function preset(start:V3,end:V3){change('view',1);start.forEach((v,i)=>change(['sx','sy','sz'][i],v));end.forEach((v,i)=>change(['ex','ey','ez'][i],v))}
 return <><div className="materials-scene-controls"><Choice label="Example source" value={p.reference} options={['Exam example','Lecture example · planes']} onChange={v=>{change('reference',v);if(v===1){change('view',2);change('planeCase',1);change('translate',1);change('structure',2)}else preset([0,0,1],[.5,0,0])}}/>{p.reference===1&&<p className="materials-note">Dr. Joshua Paul Steimel · 4:10: x=1/2, y=1, z=−1 for B; (2 1 1̅). C is (0 1 1). Geometry below recreates those observed intercepts.</p>}<Choice label="Cell" value={structure} options={['SC · A','BCC · C / D','FCC · B']} onChange={v=>{change('structure',v);if(view===3&&v!==1)change('view',0)}}/><Choice label="Inspect" value={p.view} options={['Shared atoms','Direction','Plane','BCC (200)']} onChange={v=>{change('view',v);if(v!==2)change('reference',0);if(v===3)change('structure',1)}}/>
 {view===1&&<div className="materials-tabs"><button onClick={()=>preset([0,0,0],[1,1,0])}>Easy example [110]</button>{examArrows.map(a=><button key={a.name} onClick={()=>preset(a.start,a.end)}>{a.name}</button>)}</div>}
 {view===2&&<><Choice label="Plane example" value={p.planeCase} options={['Custom / easy (100)','Exam B · FCC','Exam C · BCC']} onChange={v=>{change('planeCase',v);if(v===0){change('ix',1);change('iy',0);change('iz',0)}if(v>0)change('structure',v===1?2:1)}}/>{p.planeCase===1&&<button aria-pressed={p.translate===1} onClick={()=>change('translate',1-p.translate)}>Translate off origin</button>}</>}
 {view===3&&<div className="materials-tabs"><button onClick={()=>change('radius',Math.sqrt(3)/2)}>Easy example · a = 2 Å</button><button onClick={()=>change('radius',1)}>Unit-radius example · R = 1 Å</button></div>}
 <label className="materials-note">Rotation <input aria-label="Cell rotation slider in scene" type="range" min="-180" max="180" value={p.yaw} onChange={e=>change('yaw',Number(e.target.value))}/></label></div>
 <svg className="materials-scene" viewBox="0 0 760 440" role="img" aria-labelledby={id} onPointerDown={e=>{drag.current={x:e.clientX,yaw:p.yaw};e.currentTarget.setPointerCapture(e.pointerId);onInteractionStart()}} onPointerMove={e=>{if(drag.current)change('yaw',Math.max(-180,Math.min(180,drag.current.yaw+(e.clientX-drag.current.x)/2)))}} onPointerUp={()=>{drag.current=null;onInteractionEnd()}} onPointerCancel={()=>{drag.current=null;onInteractionEnd()}}>
 <title id={id}>{st.name} cell with {view===1?'signed direction':view===2?'Miller plane':view===3?'BCC (200) slice':'shared atoms'}</title><defs><marker id={`${id}-arrow`} markerWidth="7" markerHeight="7" refX="6" refY="3.5" orient="auto"><path d="M0,0 L7,3.5 L0,7" fill="#9db8e8"/></marker></defs>
 {edges.map(([a,b],i)=><line key={i} x1={project(a)[0]} y1={project(a)[1]} x2={project(b)[0]} y2={project(b)[1]} stroke="#444"/>)}
 {(view===2||view===3)&&poly.length>0&&<polygon points={poly.map(v=>project(v).join(',')).join(' ')} fill="#9db8e822" stroke="#9db8e8" strokeWidth="2"/>}
 {points.map((v,i)=><circle key={i} cx={project(v)[0]} cy={project(v)[1]} r={i<8?7:10} fill={i<8?'#737b8b':'#9db8e8'} opacity={view===3&&v[0]!==.5?.25:1}/>)}
 {['x','y','z'].map((label,i)=>{const o=project([0,0,0]),v:[number,number,number]=[0,0,0];v[i]=1.22;const q=project(v);return <g key={label}><line x1={o[0]} y1={o[1]} x2={q[0]} y2={q[1]} stroke="#888"/>{display.labels&&<text x={q[0]} y={q[1]-7}>{label}</text>}</g>})}
 {view===1&&<><line x1={project(start)[0]} y1={project(start)[1]} x2={project(head)[0]} y2={project(head)[1]} stroke="#9db8e8" strokeWidth="3" markerEnd={`url(#${id}-arrow)`}/><circle cx={project(end)[0]} cy={project(end)[1]} r="4" fill="#e4bd88"/>{display.forces&&<line x1={project(start)[0]} y1={project(start)[1]} x2={project(end)[0]} y2={project(end)[1]} stroke="#9db8e8" strokeDasharray="5 5" opacity=".4"/>}</>}
 {display.labels&&<><text x="520" y="120" className="large-label">{st.name}</text><text x="520" y="150">{n(st.atoms)} atoms · {n(st.nn)} NN</text><text x="520" y="175">a = {n(s.aOverR)} R</text><text x="520" y="225" className="accent">{view===1?(s.validDirection?indexText([s.u,s.v,s.w]):'Undefined direction'):view===2?(s.validPlane?indexText([s.h,s.k,s.l],true):'No finite plane'):view===3?'x = a/2':''}</text><text x="520" y="255">{view===3?'1 center / a²':view===0?'8 corners × 1/8':''}</text><text x="40" y="400">{view===1?`Δ = (${n(p.ex-p.sx)}, ${n(p.ey-p.sy)}, ${n(p.ez-p.sz)})`:view===3?'One interior atom in a square repeat area a².':view===2&&p.planeCase===1?'2x + y − z = '+n(pd.level):st.count}</text></>}
 </svg><p className="materials-note">{view===3?'BCC (200): the square contains one whole body-center atom and no corner centers. Planar atom density = 1/a²; area packing fraction = πR²/a² = 3π/16.':st.dense} {view===1&&!s.validDirection?'Coincident points or unsupported fractional coordinates: choose different rational coordinates.':''}{view===2&&!s.validPlane?'All-parallel intercepts do not define a plane.':''}</p></>
}
