import { useId, useMemo, useRef } from 'react'
import { useNumberFormat } from '../../framework/formatting'
import { SvgIndices } from './Notation'
import type { SimulationSceneProps } from '../../framework/types'
import { Choice } from '../shared/StudyPanel'
import { axisIntercepts,planeStage,tracedEdges,planeEquation } from './planeAnimation'
import { corners,edges,examArrows,structures,planeData,planePolygon,directionPoints,type V3 } from './calculation'
export function Scene({parameters:p,snapshot:s,display,onParameterChange:change,onInteractionStart,onInteractionEnd,onOpenControls}:SimulationSceneProps) {
 const {format:n}=useNumberFormat();const id=useId();const drag=useRef<{x:number;yaw:number}|null>(null);const view=Math.round(p.view),structure=view===3?1:Math.round(p.structure),st=structures[structure]
 const project=(v:V3):[number,number]=>{const a=p.yaw*Math.PI/180,x=(v[0]-.5)*Math.cos(a)-(v[1]-.5)*Math.sin(a),y=(v[0]-.5)*Math.sin(a)+(v[1]-.5)*Math.cos(a);return [(view===2?260:320)-115*x+165*y,225+65*x+25*y-185*(v[2]-.5)]}
 const points:V3[]=[...corners,...(structure===1?[[.5,.5,.5] as V3]:structure===2?[[0,.5,.5],[1,.5,.5],[.5,0,.5],[.5,1,.5],[.5,.5,0],[.5,.5,1]] as V3[]:[])]
 const {start,end}=directionPoints(p);const head=start.map((v,i)=>v+(end[i]-v)*s.progress) as V3;const pd=planeDataSafe();function planeDataSafe(){try{return planeData(p)}catch{return {normal:[0,0,0] as V3,level:1,indices:[0,0,0] as V3,indexLevel:1}}}
 const poly=useMemo(()=>view===3?planePolygon([1,0,0],.5):planePolygon(pd.normal,pd.level),[view,pd.normal[0],pd.normal[1],pd.normal[2],pd.level])
 const intercepts=useMemo(()=>axisIntercepts(pd.normal,pd.level),[pd.normal[0],pd.normal[1],pd.normal[2],pd.level]),stage=planeStage(s.progress,poly.length),trace=tracedEdges(poly,stage.edgeProgress)
 const equation=planeEquation(pd.indices,pd.indexLevel,stage.axisReveal,n),fullEquation=planeEquation(pd.indices,pd.indexLevel,[1,1,1],n)
 const coordinate=(v:V3)=>'('+v.map(n).join(', ')+')'
 const projectedCenter=poly.length?poly.map(project).reduce((sum,point)=>[sum[0]+point[0]/poly.length,sum[1]+point[1]/poly.length] as [number,number],[0,0] as [number,number]):[260,225]
 function preset(start:V3,end:V3){change('view',1);change('directionMode',0);change('reference',0);start.forEach((v,i)=>change(['sx','sy','sz'][i],v));end.forEach((v,i)=>change(['ex','ey','ez'][i],v))}
 return <><div className="materials-scene-controls"><div className="materials-choice"><span>Load a reference</span><div className="materials-tabs"><button onClick={()=>preset([0,0,1],[.5,0,0])}>Exam example · direction</button><button onClick={()=>{change('reference',1);change('view',2);change('planeCase',1);change('translate',1);change('structure',2)}}>Lecture example · planes</button></div></div>{p.reference===1&&p.planeCase===1&&view===2&&<p className="materials-note">Dr. Joshua Paul Steimel · 4:10: x=1/2, y=1, z=−1 for B; (2 1 1̅). C is (0 1 1). Geometry below recreates those observed intercepts.</p>}<Choice label="Cell" value={structure} options={['SC · A','BCC · C / D','FCC · B']} onChange={v=>{change('structure',v);if(view===3&&v!==1)change('view',0)}}/><Choice label="Inspect" value={p.view} options={['Shared atoms','Direction','Plane','BCC (200)']} onChange={v=>{change('view',v);if(v!==2)change('reference',0);if(v===3)change('structure',1)}}/>
 {view===1&&<div className="materials-tabs"><button onClick={()=>preset([0,0,0],[1,1,0])}>Easy example [110]</button>{examArrows.map(a=><button key={a.name} onClick={()=>preset(a.start,a.end)}>{a.name}</button>)}</div>}
 {view===2&&<><Choice label="Plane example" value={p.planeCase} options={['My plane','Exam B · FCC','Exam C · BCC']} onChange={v=>{change('planeCase',v);change('reference',0);if(v===1)change('translate',0);if(v>0)change('structure',v===1?2:1)}}/>{p.planeCase===1&&<button aria-pressed={p.translate===1} onClick={()=>change('translate',1-p.translate)}>Translate off origin</button>}</>}
 {view===3&&<div className="materials-tabs"><button onClick={()=>change('radius',Math.sqrt(3)/2)}>Easy example · a = 2 Å</button><button onClick={()=>change('radius',1)}>Unit-radius example · R = 1 Å</button></div>}
 {onOpenControls&&(view===1||view===2)&&<button className="crystal-open-editor" onClick={()=>{if(view===2){change('planeCase',0);change('reference',0)}onOpenControls()}}>Create your own {view===1?'direction':'plane'} ↗</button>}
 <label className="materials-note">Rotation <input aria-label="Cell rotation slider in scene" type="range" min="-180" max="180" value={p.yaw} onChange={e=>change('yaw',Number(e.target.value))}/></label></div>
 <svg className="materials-scene" viewBox={view===2?"0 0 600 480":"0 0 760 440"} role="img" aria-labelledby={id} onPointerDown={e=>{drag.current={x:e.clientX,yaw:p.yaw};e.currentTarget.setPointerCapture(e.pointerId);onInteractionStart()}} onPointerMove={e=>{if(drag.current)change('yaw',Math.max(-180,Math.min(180,drag.current.yaw+(e.clientX-drag.current.x)/2)))}} onPointerUp={()=>{drag.current=null;onInteractionEnd()}} onPointerCancel={()=>{drag.current=null;onInteractionEnd()}}>
 <title id={id}>{st.name} cell with {view===1?'signed direction':view===2?'Miller plane':view===3?'BCC (200) slice':'shared atoms'}</title><defs><marker id={`${id}-arrow`} markerWidth="7" markerHeight="7" refX="6" refY="3.5" orient="auto"><path d="M0,0 L7,3.5 L0,7" fill="#9db8e8"/></marker></defs>
 {edges.map(([a,b],i)=><line key={i} x1={project(a)[0]} y1={project(a)[1]} x2={project(b)[0]} y2={project(b)[1]} stroke="#444"/>)}
 {view===3&&poly.length>0&&<polygon points={poly.map(v=>project(v).join(',')).join(' ')} fill="#9db8e822" stroke="#9db8e8" strokeWidth="2"/>}
 {view===2&&s.validPlane===1&&<>{poly.length>0&&<polygon data-plane-fill points={poly.map(v=>project(v).join(',')).join(' ')} fill="#9db8e8" fillOpacity={stage.fillOpacity} stroke="none"/>}{trace.map((segment,i)=><line data-plane-edge key={i} x1={project(segment.start)[0]} y1={project(segment.start)[1]} x2={project(segment.end)[0]} y2={project(segment.end)[1]} stroke="#a8c6f4" strokeWidth="2.5"/>)}</>}
 {points.map((v,i)=><circle key={i} cx={project(v)[0]} cy={project(v)[1]} r={i<8?7:10} fill={i<8?'#737b8b':'#9db8e8'} opacity={view===3&&v[0]!==.5?.25:1}/>)}
 {['x','y','z'].map((label,i)=>{const o=project([0,0,0]),v:[number,number,number]=[0,0,0];v[i]=1.22;const q=project(v);return <g key={label}><line x1={o[0]} y1={o[1]} x2={q[0]} y2={q[1]} stroke="#888"/>{display.labels&&<text x={q[0]} y={q[1]-7}>{label}</text>}</g>})}
 {view===2&&s.validPlane===1&&intercepts.map((intercept,i)=>{
  if(!intercept.point||!intercept.insideCell)return null
  if(intercept.value===0&&intercepts.slice(0,i).some(other=>other.kind==='finite'&&other.value===0))return null
  const o=project([0,0,0]),q=project(intercept.point),opacity=stage.axisReveal[i]*Math.min(1,Math.max(0,1-(stage.progress-.32)/.16)),end=intercept.point.map(value=>value*stage.axisReveal[i]) as V3
  return <g key={intercept.axis} opacity={opacity}><line x1={o[0]} y1={o[1]} x2={project(end)[0]} y2={project(end)[1]} stroke="#d4b184" strokeDasharray="4 3"/><circle cx={q[0]} cy={q[1]} r="5" fill="#d4b184"/>{display.labels&&<text x={q[0]+9} y={q[1]-12} style={{fill:'#e4c390'}}>{intercept.value===0?'O (0, 0, 0)':intercept.axis+' = '+n(intercept.value!)}</text>}</g>
 })}
 {view===2&&s.validPlane===1&&poly.map((point,i)=>{const q=project(point),left=q[0]<projectedCenter[0],above=q[1]<projectedCenter[1],text=coordinate(point);return <g key={i} opacity={stage.vertexReveal[i]}><circle data-plane-vertex cx={q[0]} cy={q[1]} r="4.5" fill="#c8def9"/>{display.labels&&<text x={q[0]+(left?-9:9)} y={q[1]+(above?-15:23)} textAnchor={left?'end':'start'} style={{fill:'#c8def9',fontSize:12}}>V{i+1}{text.length<=22?' '+text:''}</text>}</g>})}
 {view===1&&<><line x1={project(start)[0]} y1={project(start)[1]} x2={project(head)[0]} y2={project(head)[1]} stroke="#9db8e8" strokeWidth="3" markerEnd={`url(#${id}-arrow)`}/><circle cx={project(end)[0]} cy={project(end)[1]} r="4" fill="#e4bd88"/>{display.forces&&<line x1={project(start)[0]} y1={project(start)[1]} x2={project(end)[0]} y2={project(end)[1]} stroke="#9db8e8" strokeDasharray="5 5" opacity=".4"/>}</>}
 {display.labels&&view===2&&<><text x="30" y="25">{st.name} · {n(st.atoms)} atoms/cell · a = {n(s.aOverR)} R</text>{s.validPlane===1&&<text x="450" y="60" className="accent" style={{fontSize:17}} opacity={Math.min(...stage.axisReveal)}><SvgIndices values={[s.h,s.k,s.l]} plane/></text>}<text x="30" y="422" style={{fill:'#c8def9'}}>{s.validPlane?stage.label:'Set a nonzero plane normal'}</text>{s.validPlane===1&&equation.length<=65&&<text x="30" y="453" style={{fontSize:15,fill:'#e5edfa'}}>{equation}</text>}</>}
 {display.labels&&view!==2&&<><text x="520" y="120" className="large-label">{st.name}</text><text x="520" y="150">{n(st.atoms)} atoms · {n(st.nn)} NN</text><text x="520" y="175">a = {n(s.aOverR)} R</text><text x="520" y="225" className="accent">{view===1?(s.validDirection?<SvgIndices values={[s.u,s.v,s.w]}/>: 'Undefined direction'):view===3?'x = a/2':''}</text><text x="520" y="255">{view===3?'1 center / a²':view===0?'8 corners × 1/8':''}</text><text x="40" y="400">{view===1?`Δ = (${n(end[0]-start[0])}, ${n(end[1]-start[1])}, ${n(end[2]-start[2])})`:view===3?'One interior atom in a square repeat area a².':st.count}</text></>}
 </svg>{view===2&&s.validPlane===1&&<div className="materials-note crystal-construction" style={{paddingTop:16}}>
 <p style={{margin:'0 0 8px'}}>{stage.label} · coordinates use lattice units (x/a, y/a, z/a).</p>
 {display.labels&&<><p style={{color:'#d8e6fa',fontFamily:'ui-monospace, monospace',fontSize:16,overflowWrap:'anywhere',margin:'8px 0'}} aria-label={'Plane equation under construction; complete equation '+fullEquation}>{equation}</p>
 <table className="materials-facts" aria-label="Plane axis intercepts"><thead><tr><th>Axis</th><th>Intercept</th><th>Location</th></tr></thead><tbody>{intercepts.map((intercept,i)=><tr key={intercept.axis} style={{opacity:stage.axisReveal[i]}}><th scope="row">{intercept.axis}</th><td>{intercept.kind==='parallel'?'∞':intercept.kind==='contained'?'No unique intercept':n(intercept.value!)}</td><td>{intercept.kind==='parallel'?'Parallel axis':intercept.kind==='contained'?'Whole axis lies in plane':intercept.insideCell?'In shown cell':'Outside shown cell'}</td></tr>)}</tbody></table>
 {poly.length>0&&<table className="materials-facts" aria-label="Clipped plane vertex coordinates" style={{marginTop:12}}><thead><tr><th>Cell-clipped vertex</th><th>x</th><th>y</th><th>z</th></tr></thead><tbody>{poly.map((point,i)=><tr key={i} style={{opacity:stage.vertexReveal[i]}}><th scope="row">V{i+1}</th>{point.map((value,k)=><td key={k}>{n(value)}</td>)}</tr>)}</tbody></table>}
 <p>V labels identify the cell-clipped patch vertices; they are not all axis intercepts. Negative or distant intercepts stay in the list rather than being moved into the cell.</p></>}
 {pd.level===0&&<p>The finite axis intercepts collapse at the origin. Translate the plane to read nonzero intercepts; its orientation stays the same.</p>}
 {pd.level===0&&p.planeCase===0&&p.planeInput===1&&<button className="crystal-open-editor" onClick={()=>change('planeLevel',1)}>Translate to offset 1</button>}
 {poly.length===0&&<p>This valid equation has no positive-area patch inside the shown cell; it can miss the cell or only touch an edge or vertex. Change the offset to see a slice.</p>}
 </div>}<p className="materials-note">{view===3?'BCC (200): the square contains one whole body-center atom and no corner centers. Planar atom density = 1/a²; area packing fraction = πR²/a² = 3π/16.':st.dense} {view===1&&!s.validDirection?'Coincident points or unsupported fractional coordinates: choose different rational coordinates.':''}{view===2&&!s.validPlane?'All-parallel intercepts do not define a plane.':''}</p></>
}
